#!/usr/bin/env bash
# Render Homebrew and WinGet release manifests from a release checksum file.

set -euo pipefail

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <tag> <checksums.txt> <out-dir>" >&2
    exit 2
fi

tag="$1"
checksums_path="$2"
output_dir="$3"
bare_version="${tag#v}"
repo="monkey1wizard/web-design-anchor"

if [ ! -f "$checksums_path" ]; then
    echo "render-manifests: checksum file not found: $checksums_path" >&2
    exit 1
fi

checksum_for() {
    local archive="$1"
    awk -v archive="$archive" '$2 == archive || $2 == "*" archive { print $1; exit }' "$checksums_path"
}

darwin_x64="$(checksum_for "wda-${tag}-darwin-x64.tar.gz")"
darwin_arm64="$(checksum_for "wda-${tag}-darwin-arm64.tar.gz")"
linux_x64="$(checksum_for "wda-${tag}-linux-x64.tar.gz")"
linux_arm64="$(checksum_for "wda-${tag}-linux-arm64.tar.gz")"
windows_x64="$(checksum_for "wda-${tag}-windows-x64.zip")"
windows_arm64="$(checksum_for "wda-${tag}-windows-arm64.zip")"

for entry in \
    "darwin-x64:${darwin_x64}" \
    "darwin-arm64:${darwin_arm64}" \
    "linux-x64:${linux_x64}" \
    "linux-arm64:${linux_arm64}" \
    "windows-x64:${windows_x64}" \
    "windows-arm64:${windows_arm64}"; do
    name="${entry%%:*}"
    value="${entry#*:}"
    if [ -z "$value" ]; then
        echo "render-manifests: missing checksum for ${name}" >&2
        exit 1
    fi
done

mkdir -p "$output_dir"

formula_path="$output_dir/wda-${tag}.rb"
cat > "$formula_path" <<EOF
# Homebrew formula for WDA
# Generated by: WDA release pipeline
class Wda < Formula
  desc "Framework-independent web design workflow CLI"
  homepage "https://github.com/${repo}"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/${repo}/releases/download/${tag}/wda-${tag}-darwin-arm64.tar.gz"
      sha256 "${darwin_arm64}"
    else
      url "https://github.com/${repo}/releases/download/${tag}/wda-${tag}-darwin-x64.tar.gz"
      sha256 "${darwin_x64}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/${repo}/releases/download/${tag}/wda-${tag}-linux-arm64.tar.gz"
      sha256 "${linux_arm64}"
    else
      url "https://github.com/${repo}/releases/download/${tag}/wda-${tag}-linux-x64.tar.gz"
      sha256 "${linux_x64}"
    end
  end

  def install
    bin.install "wda"
    pkgshare.install Dir["*"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wda --version")
    assert_predicate pkgshare/"skills", :directory?
  end
end
EOF

manifest_dir="$output_dir/manifests/m/Monkey1Wizard/WDA/${bare_version}"
mkdir -p "$manifest_dir"

cat > "$manifest_dir/Monkey1Wizard.WDA.yaml" <<EOF
PackageIdentifier: Monkey1Wizard.WDA
PackageVersion: "${bare_version}"
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
EOF

cat > "$manifest_dir/Monkey1Wizard.WDA.installer.yaml" <<EOF
PackageIdentifier: Monkey1Wizard.WDA
PackageVersion: "${bare_version}"
Commands:
  - wda
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: "wda.exe"
    PortableCommandAlias: wda
Installers:
  - Architecture: x64
    InstallerUrl: "https://github.com/${repo}/releases/download/${tag}/wda-${tag}-windows-x64.zip"
    InstallerSha256: "${windows_x64}"
  - Architecture: arm64
    InstallerUrl: "https://github.com/${repo}/releases/download/${tag}/wda-${tag}-windows-arm64.zip"
    InstallerSha256: "${windows_arm64}"
ManifestType: installer
ManifestVersion: 1.6.0
EOF

cat > "$manifest_dir/Monkey1Wizard.WDA.locale.en-US.yaml" <<EOF
PackageIdentifier: Monkey1Wizard.WDA
PackageVersion: "${bare_version}"
PackageLocale: en-US
Publisher: Monkey1Wizard
PublisherUrl: "https://github.com/monkey1wizard"
PublisherSupportUrl: "https://github.com/${repo}/issues"
PackageName: WDA
PackageUrl: "https://github.com/${repo}"
License: Apache-2.0
LicenseUrl: "https://github.com/${repo}/blob/main/LICENSE"
ShortDescription: "WDA framework-independent web design workflow CLI"
Description: >-
  WDA is a framework-independent web design workflow CLI for building standard
  web projects with HTML5, modern CSS, and TypeScript.
Moniker: wda
Tags:
  - ai
  - cli
  - developer-tools
  - web-design
ManifestType: defaultLocale
ManifestVersion: 1.6.0
EOF

printf 'Rendered Homebrew formula and WinGet manifests for %s\n' "$tag"
